[package]
name = "tugger-file-manifest"
version = "0.7.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
readme = "README.md"
description = "Interact with lists of files through a storage-agnostic interface"
keywords = ["package", "tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"

[dev-dependencies]
tempfile = "3.2"
