[package]
name = "tugger-wix"
version = "0.14.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Interfaces to the WiX Toolset to produce Windows installers"
keywords = ["package", "tugger", "windows", "wix", "wix-toolset"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"
build = "build.rs"

[dependencies]
anyhow = "1.0"
duct = "0.13"
log = "0.4"
once_cell = "1.7"
url = "2.2"
uuid = { version = "1.1", features = ["v4", "v5"] }
xml-rs = "0.8"

[dependencies.tugger-common]
version = "0.10.0-pre"
path = "../tugger-common"

[dependencies.tugger-windows-codesign]
version = "0.8.0"
# path = "../tugger-windows-codesign"

[dependencies.tugger-windows]
version = "0.9.0"
# path = "../tugger-windows"

[dependencies.tugger-file-manifest]
version = "0.10.0-pre"
path = "../tugger-file-manifest"

[dev-dependencies]
tempfile = "3.2"

[target.'cfg(windows)'.dev-dependencies]
msi = "0.4"
