[workspace]
members = [
    'cryptographic-message-syntax',
    'pyembed',
    'pyoxidizer',
    'python-packaging',
    'python-packed-resources',
    'release',
    'starlark-dialect-build-targets',
    'text-stub-library',
    'tugger',
    'tugger-apple',
    'tugger-apple-bundle',
    'tugger-apple-codesign',
    'tugger-binary-analysis',
    'tugger-code-signing',
    'tugger-common',
    'tugger-debian',
    'tugger-file-manifest',
    'tugger-licensing',
    'tugger-licensing-net',
    'tugger-rpm',
    'tugger-rust-toolchain',
    'tugger-snapcraft',
    'tugger-windows',
    'tugger-windows-codesign',
    'tugger-wix',
    'x509-certificate',
]
