[workspace]
members = [
    'oxidized-importer',
    'pyembed',
    'pyoxidizer',
    'python-packaging',
    'python-packed-resources',
    'release',
    'starlark-dialect-build-targets',
    'tugger',
    'tugger-apple',
    'tugger-binary-analysis',
    'tugger-common',
    'tugger-debian',
    'tugger-file-manifest',
    'tugger-licensing',
    'tugger-licensing-net',
    'tugger-rpm',
    'tugger-snapcraft',
    'tugger-windows',
    'tugger-wix',
]
