[package]
name = "tugger-apple"
version = "0.5.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Random functionality related to Apple platforms"
keywords = ["tugger", "apple", "macos"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
duct = "0.13"
goblin = "0.4"
once_cell = "1.7"
scroll = "0.10"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
