[package]
name = "x509-certificate"
version = "0.14.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "X.509 certificate parser and utility functionality"
keywords = ["x509", "cryptography", "pki"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[features]
test = []

[dependencies]
bcder = "0.7"
bytes = "1.0"
chrono = "0.4"
der = "0.5"
hex = "0.4"
pem = "1.0"
ring = "0.16"
signature = "1.3"
spki = { version = "0.5", features = ["alloc"] }
thiserror = "1.0"
