[package]
name = "tugger-rust-toolchain"
version = "0.8.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Discover, download, and use Rust toolchains"
keywords = ["rustup"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
flate2 = "1.0"
fs2 = "0.4"
hex = "0.4"
once_cell = "1.7"
pgp = "0.7"
sha2 = "0.10"
slog = "2.7"
tar = "0.4"
toml = "0.5"
xz2 = "0.1"
zstd = "0.9"

[dependencies.tugger-common]
version = "0.8.0"
# path = "../tugger-common"

[dependencies.tugger-file-manifest]
version = "0.7.0"
# path = "../tugger-file-manifest"

[dev-dependencies]
dirs = "4.0"
tempfile = "3.2"
