[package]
name = "pyapp"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
jemallocator-global = "0.3"
lazy_static = "1.3"
pyembed = { path = "../pyembed" }
