[package]
name = "tugger"
version = "0.17.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Package and distribute applications"
keywords = ["package"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"
build = "build.rs"

[dependencies]
anyhow = "1.0"
atty = "0.2"
codemap = "0.1"
codemap-diagnostic = "0.1"
console = "0.15"
dialoguer = "0.10"
linked-hash-map = "0.5"
log = "0.4"
plist = "1.2"
starlark = "0.3.1"
tar = "0.4"
tempfile = "3.2"
time = "0.3"
walkdir = "2"

[dependencies.apple-bundles]
version = "0.13.0"
# path = "../apple-bundles"

[dev-dependencies.apple-codesign]
version = "0.18.0-pre"
path = "../apple-codesign"

[dependencies.python-packaging]
version = "0.15.0-pre"
path = "../python-packaging"

[dependencies.starlark-dialect-build-targets]
version = "0.7.0"
# path = "../starlark-dialect-build-targets"

[dependencies.tugger-apple]
version = "0.8.0-pre"
path = "../tugger-apple"

[dependencies.tugger-code-signing]
version = "0.9.0-pre"
path = "../tugger-code-signing"

[dependencies.tugger-common]
version = "0.9.0"
# path = "../tugger-common"

[dependencies.tugger-snapcraft]
version = "0.13.0"
# path = "../tugger-snapcraft"

[dependencies.tugger-windows]
version = "0.10.0-pre"
path = "../tugger-windows"

[dependencies.tugger-wix]
version = "0.15.0-pre"
path = "../tugger-wix"

[dependencies.tugger-file-manifest]
version = "0.10.0"
# path = "../tugger-file-manifest"

[dev-dependencies]
chrono = "0.4"
tempfile = "3.2"

[dev-dependencies.tugger-windows-codesign]
version = "0.9.0-pre"
path = "../tugger-windows-codesign"

[dev-dependencies.x509-certificate]
version = "0.15.0"
# path = "../x509-certificate"
