[package]
name = "tugger-common"
version = "0.2.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Common functionality used by various tugger crates"
keywords = ["tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
fs2 = "0.4"
glob = "0.3"
hex = "0.4"
once_cell = "1.7"
reqwest = { version = "0.11", default-features= false, features = ["blocking", "rustls-tls"] }
sha2 = "0.9"
slog = "2.7"
tempfile = "3.2"
url = "2.2"
zip = "0.5"
