on:
  push:
  pull_request:
  schedule:
    - cron: '13 15 * * *'
jobs:
  wheel_linux:
    strategy:
      fail-fast: false
      matrix:
        py:
          - build: 'cp38-manylinux_x86_64'
            version: '3.8'
          - build: 'cp39-manylinux_x86_64'
            version: '3.9'
    runs-on: ubuntu-20.04
    env:
      CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
      CIBW_BEFORE_BUILD: 'ci/install-rust-linux.sh'
      CIBW_BUILD: ${{ matrix.py.build }}
      CIBW_BUILD_VERBOSITY: '1'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py.version }}
      - name: Run cibuildwheel
        run: |
          python${{ matrix.py.version }} -m pip install --upgrade pip==21.2.4
          python${{ matrix.py.version }} -m pip install cibuildwheel==2.1.2
          python${{ matrix.py.version }} -m cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: |
            wheelhouse

  wheel_macos:
    strategy:
      fail-fast: false
      matrix:
        py:
          - build: 'cp38-macosx_x86_64'
            version: '3.8'
          - build: 'cp39-macosx_x86_64'
            version: '3.9'
    runs-on: macos-11
    env:
      CIBW_BUILD: ${{ matrix.py.build }}
      CIBW_BUILD_VERBOSITY: '1'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py.version }}
      - name: Run cibuildwheel
        run: |
          python${{ matrix.py.version }} -m pip install --upgrade pip==21.2.4
          python${{ matrix.py.version }} -m pip install cibuildwheel==2.1.2
          python${{ matrix.py.version }} -m cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: |
            wheelhouse

  wheel_windows:
    strategy:
      fail-fast: false
      matrix:
        py:
          - build: 'cp38-win_amd64'
            version: '3.8'
          - build: 'cp39-win_amd64'
            version: '3.9'
    runs-on: windows-2019
    env:
      CIBW_BUILD_VERBOSITY: '1'
      CIBW_BUILD: ${{ matrix.py.build }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py.version }}
      - name: Run cibuildwheel
        run: |
          python -m pip install --upgrade pip==21.2.4
          python -m pip install cibuildwheel==2.1.2
          python -m cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: |
            wheelhouse
